apiVersion: v1
kind: ConfigMap
metadata:
  name: sadevbot-config
  namespace: sadevs
data:
  BOT_DIR: '/k8s-volume'
  BOT_MODE: 'SlackRTM'
  BOT_ADMINS: &BOT_ADMINS '@drlordrevandrew,@gtmanfred,@redrobot,@bigjonroberts'
  BOT_ALT_PREFIXES: '@sadevbot'
  LOG_LEVEL: "debug"
  TOPIC_CHANNEL: '#topic-a-day'
  TOPIC_SCHEDULE: '0 14 * * 0,2,4'
  TOPIC_TZ: 'US/Central'
  THREADED_COMMANDS: 'log tail,status plugins,status'
  REPORT_CHANNEL: "#admins"
  extra-requirements.txt: |
    errbot[slack-rtm]
  access_controls.json: |
    {
      'Plugins:*': { 'allowusers': *BOT_ADMINS },
      'Health:*': { 'allowusers': *BOT_ADMINS },
      'Utils:*': { 'allowusers': *BOT_ADMINS }
    }
  plugins.json: |
        {
                "git_repos": [{
                        "name": "sadevbot-plugins",
                        "url": "https://github.com/SADevs/sadevbot-plugins.git",
                        "branch": "v0.2"
                }, {
                        "name": "topic-a-day",
                        "url": "https://github.com/andrewthetechie/err-topic-a-day.git",
                        "branch": "v0.2"
                }, {
                        "name": "anonymous-report",
                        "url": "https://github.com/andrewthetechie/err-anonymous-report.git",
                        "branch": "master"
                }]
        }
