---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sadevbot-pvc
  namespace: sadevs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sadevbot-deployment
  namespace: sadevs
  labels:
    app: sadevbot
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: sadevbot
  template:
    metadata:
      labels:
        app: sadevbot
    spec:
      containers:
      - name: sadevbot
        image: andrewthetechie/errbot-k8s:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - git config --global user.email "sadevbot@sanantoniodevs.com"&& git config --global user.name "SADevBot" && ssh-keyscan github.com >> ~/.ssh/known_hosts && cp /var/ssh-keys/website-deploy-key /root/.ssh/id_ed25519
        envFrom:
        - configMapRef:
            name: sadevbot-config
        env:
        - name: 'ACCESS_CONTROL_FILE'
          value: '/config/access_controls.json'
        - name: 'SLACK_TOKEN'
          valueFrom:
            secretKeyRef:
              name: sadevbot-secret
              key: slack-token
        - name: 'GITHUB_TOKEN'
          valueFrom:
            secretKeyRef:
              name: sadevbot-secret
              key: github-token
        ports:
        - containerPort: 80
          name: sadevbot-http
        volumeMounts:
            - mountPath: "/k8s-volume"
              name: sadevbot-pvc
            - name: config
              mountPath: /config
            - name: website-deploy-key
              mountPath: /var/ssh-keys
      volumes:
        - name: sadevbot-pvc
          persistentVolumeClaim:
            claimName: sadevbot-pvc
        - name: website-deploy-key
          secret:
            secretName: sadevbot-secret
            items:
            - key: website-deploy-key
              path: website-deploy-key 
              mode: 0600
        - name: config
          configMap:
            name: sadevbot-config
            items:
              - key: plugins.json
                path: plugins.json
              - key: access_controls.json
                path: access_controls.json
              - key: extra-requirements.txt
                path: extra-requirements.txt
              - key: apscheduler-config.json
                path: apscheduler-config.json
